services:
  postgres:
    image: surimadhira/postgres:0.9
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  rabbitmq:
    image: surimadhira/rabbitmq:0.9
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
      - 15671:15671
    depends_on:
      - postgres
      
  am:
    hostname: am
    image: surimadhira/openam:0.9
    restart: on-failure
    volumes:
      - am-data:/usr/ssosec/config
    ports:
      - 8082:8080
      - 50389:50389
      - 4444:4444
      - 1689:1689
    depends_on:
      - rabbitmq

 webclient:
    image: surimadhira/webclient:0.9
    ports:
      - 8888:8888
    depends_on:
      - am

  reporting:
    image: surimadhira/rna:0.9
    ports:
      - 8301:8301
    depends_on:
      - am

  amqp:
    image: surimadhira/amqp:0.9
    depends_on:
      - am

  rmqconsumer:
    image: surimadhira/rmqconsumer:0.9
    depends_on:
      - am
      
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 8443:443
    restart: always
    volumes:
      - ../nginx/conf/:/etc/nginx/conf.d/
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs/:/etc/nginx/ssl/:ro


volumes:
  db-data:
  am-data:
