services:
  postgres:
    image: ssosecsystems/postgres:dev
    container_name: postgres
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  rabbitmq:
    image: ssosecsystems/rabbitmq:dev
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
      - 15671:15671
    depends_on:
      - postgres
      
  am:
    hostname: am
    image: ssosecsystems/openam:dev
    container_name: am
    hostname: am
    restart: on-failure
    volumes:
      - am-data:/usr/ssosec/config
      - ../rmqconsumer/:/etc/rmqconfig/
    ports:
      - 8081:8080
      - 50389:50389
      - 4444:4444
      - 1689:1689
    depends_on:
      - rabbitmq

  webclient:
    image: ssosecsystems/webclient:dev
    container_name: webclient
    ports:
      - 8888:8888
    depends_on:
      - am
    volumes:
      - ../installer/:/resources/

  trust:
    image: ssosecsystems/rna:dev
    container_name: trust
    ports:
      - 9999:9999
    depends_on:
      - am
    volumes:
      - ../installer/:/resources/
      - ../openssl/keystore/:/certs/


  rmqconsumer:
    image: ssosecsystems/rmqconsumer:dev
    container_name: rmqconsumer
    depends_on:
      - am
    volumes:
      - ../rmqconsumer/:/etc/rmqconfig/
      
  onboardapp:
    image: ssosecsystems/onboardapp:dev
    container_name: onboardapp
    ports:
      - 8889:8889
    depends_on:
      - am
    volumes:
      - ../rmqconsumer/:/etc/rmqconfig/
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ../nginx/conf/:/etc/nginx/conf.d/
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs/:/etc/nginx/ssl/:ro
      - ../openssl/intermediate/certs/:/certs/
      
  vault:
          container_name: vault
          image: hashicorp/vault:latest
          ports:
              - "8200:8200"
          cap_add:
              - IPC_LOCK
          volumes:
              - ../vault/config:/config
          command: server -config=/config/vault.hcl


volumes:
  db-data:
  am-data:
