services:
  postgres:
    image: surimadhira/postgres:dev
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  rabbitmq:
    image: surimadhira/rabbitmq:dev
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
      - 15671:15671

  ctrl.ssosec.com:
    hostname: ctrl.ssosec.com
    image: surimadhira/openam:dev
    restart: on-failure
    volumes:
      - openam-data:/usr/openam/config
    ports:
      - 8080:8080
      - 50389:50389
      - 4444:4444
      - 1689:1689


  webclient:
    image: surimadhira/webclient:dev
    ports:
      - 80:8888
      - 443:8443
    volumes:
      - ~/certs:/certificates

  reporting:
    image: surimadhira/rna:dev
    ports:
      - 8301:8301

  amqp:
    image: surimadhira/amqp:dev

  rmqconsumer:
    image: surimadhira/rmqconsumer:dev


volumes:
  db-data:
  openam-data:
